version: '2.1'
services:
  database:
    image: postgres:9.6.5-alpine
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=realponto-core-postgres

  databaseTest:
    image: postgres:9.6.5-alpine
    ports:
    - 5430:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=realponto-core-postgres-test

  redis:
    image: redis
    ports:
    - 6379:6379