version: '2.1'
services:
  database:
    image: postgres:latest
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=realponto-core-postgres
      